server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:A958836z!@tcp(125.88.204.51:3306)/sd-point?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 125.88.204.51:6379
    password: Redis123456!
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
auth:
  jwt_key: myJwtKeyForTest