// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: api/sd-point/admin/v1/sd-point_admin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSdPointAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSdPointAdminRequest) Reset() {
	*x = CreateSdPointAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSdPointAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSdPointAdminRequest) ProtoMessage() {}

func (x *CreateSdPointAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSdPointAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateSdPointAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{0}
}

type CreateSdPointAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSdPointAdminReply) Reset() {
	*x = CreateSdPointAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSdPointAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSdPointAdminReply) ProtoMessage() {}

func (x *CreateSdPointAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSdPointAdminReply.ProtoReflect.Descriptor instead.
func (*CreateSdPointAdminReply) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{1}
}

type UpdateSdPointAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSdPointAdminRequest) Reset() {
	*x = UpdateSdPointAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSdPointAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSdPointAdminRequest) ProtoMessage() {}

func (x *UpdateSdPointAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSdPointAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateSdPointAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{2}
}

type UpdateSdPointAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSdPointAdminReply) Reset() {
	*x = UpdateSdPointAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSdPointAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSdPointAdminReply) ProtoMessage() {}

func (x *UpdateSdPointAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSdPointAdminReply.ProtoReflect.Descriptor instead.
func (*UpdateSdPointAdminReply) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{3}
}

type DeleteSdPointAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSdPointAdminRequest) Reset() {
	*x = DeleteSdPointAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSdPointAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSdPointAdminRequest) ProtoMessage() {}

func (x *DeleteSdPointAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSdPointAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteSdPointAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{4}
}

type DeleteSdPointAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSdPointAdminReply) Reset() {
	*x = DeleteSdPointAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSdPointAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSdPointAdminReply) ProtoMessage() {}

func (x *DeleteSdPointAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSdPointAdminReply.ProtoReflect.Descriptor instead.
func (*DeleteSdPointAdminReply) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{5}
}

type GetSdPointAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSdPointAdminRequest) Reset() {
	*x = GetSdPointAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSdPointAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSdPointAdminRequest) ProtoMessage() {}

func (x *GetSdPointAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSdPointAdminRequest.ProtoReflect.Descriptor instead.
func (*GetSdPointAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{6}
}

type GetSdPointAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSdPointAdminReply) Reset() {
	*x = GetSdPointAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSdPointAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSdPointAdminReply) ProtoMessage() {}

func (x *GetSdPointAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSdPointAdminReply.ProtoReflect.Descriptor instead.
func (*GetSdPointAdminReply) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{7}
}

type ListSdPointAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSdPointAdminRequest) Reset() {
	*x = ListSdPointAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSdPointAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSdPointAdminRequest) ProtoMessage() {}

func (x *ListSdPointAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSdPointAdminRequest.ProtoReflect.Descriptor instead.
func (*ListSdPointAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{8}
}

type ListSdPointAdminReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSdPointAdminReply) Reset() {
	*x = ListSdPointAdminReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSdPointAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSdPointAdminReply) ProtoMessage() {}

func (x *ListSdPointAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSdPointAdminReply.ProtoReflect.Descriptor instead.
func (*ListSdPointAdminReply) Descriptor() ([]byte, []int) {
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP(), []int{9}
}

var File_api_sd_point_admin_v1_sd_point_admin_proto protoreflect.FileDescriptor

var file_api_sd_point_admin_v1_sd_point_admin_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64, 0x2d, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x64, 0x2d, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x64, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x19, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x64, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a,
	0x17, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0xd7, 0x04, 0x0a, 0x0c, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x76, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x76, 0x0a, 0x12, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x76, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6d, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x2d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x70, 0x0a, 0x10, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x2e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x64, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x64, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x23, 0x5a, 0x21, 0x73,
	0x64, 0x2d, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64, 0x2d, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescOnce sync.Once
	file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescData = file_api_sd_point_admin_v1_sd_point_admin_proto_rawDesc
)

func file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescGZIP() []byte {
	file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescOnce.Do(func() {
		file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescData)
	})
	return file_api_sd_point_admin_v1_sd_point_admin_proto_rawDescData
}

var file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_sd_point_admin_v1_sd_point_admin_proto_goTypes = []interface{}{
	(*CreateSdPointAdminRequest)(nil), // 0: api.sd_point.admin.v1.CreateSdPointAdminRequest
	(*CreateSdPointAdminReply)(nil),   // 1: api.sd_point.admin.v1.CreateSdPointAdminReply
	(*UpdateSdPointAdminRequest)(nil), // 2: api.sd_point.admin.v1.UpdateSdPointAdminRequest
	(*UpdateSdPointAdminReply)(nil),   // 3: api.sd_point.admin.v1.UpdateSdPointAdminReply
	(*DeleteSdPointAdminRequest)(nil), // 4: api.sd_point.admin.v1.DeleteSdPointAdminRequest
	(*DeleteSdPointAdminReply)(nil),   // 5: api.sd_point.admin.v1.DeleteSdPointAdminReply
	(*GetSdPointAdminRequest)(nil),    // 6: api.sd_point.admin.v1.GetSdPointAdminRequest
	(*GetSdPointAdminReply)(nil),      // 7: api.sd_point.admin.v1.GetSdPointAdminReply
	(*ListSdPointAdminRequest)(nil),   // 8: api.sd_point.admin.v1.ListSdPointAdminRequest
	(*ListSdPointAdminReply)(nil),     // 9: api.sd_point.admin.v1.ListSdPointAdminReply
}
var file_api_sd_point_admin_v1_sd_point_admin_proto_depIdxs = []int32{
	0, // 0: api.sd_point.admin.v1.SdPointAdmin.CreateSdPointAdmin:input_type -> api.sd_point.admin.v1.CreateSdPointAdminRequest
	2, // 1: api.sd_point.admin.v1.SdPointAdmin.UpdateSdPointAdmin:input_type -> api.sd_point.admin.v1.UpdateSdPointAdminRequest
	4, // 2: api.sd_point.admin.v1.SdPointAdmin.DeleteSdPointAdmin:input_type -> api.sd_point.admin.v1.DeleteSdPointAdminRequest
	6, // 3: api.sd_point.admin.v1.SdPointAdmin.GetSdPointAdmin:input_type -> api.sd_point.admin.v1.GetSdPointAdminRequest
	8, // 4: api.sd_point.admin.v1.SdPointAdmin.ListSdPointAdmin:input_type -> api.sd_point.admin.v1.ListSdPointAdminRequest
	1, // 5: api.sd_point.admin.v1.SdPointAdmin.CreateSdPointAdmin:output_type -> api.sd_point.admin.v1.CreateSdPointAdminReply
	3, // 6: api.sd_point.admin.v1.SdPointAdmin.UpdateSdPointAdmin:output_type -> api.sd_point.admin.v1.UpdateSdPointAdminReply
	5, // 7: api.sd_point.admin.v1.SdPointAdmin.DeleteSdPointAdmin:output_type -> api.sd_point.admin.v1.DeleteSdPointAdminReply
	7, // 8: api.sd_point.admin.v1.SdPointAdmin.GetSdPointAdmin:output_type -> api.sd_point.admin.v1.GetSdPointAdminReply
	9, // 9: api.sd_point.admin.v1.SdPointAdmin.ListSdPointAdmin:output_type -> api.sd_point.admin.v1.ListSdPointAdminReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_sd_point_admin_v1_sd_point_admin_proto_init() }
func file_api_sd_point_admin_v1_sd_point_admin_proto_init() {
	if File_api_sd_point_admin_v1_sd_point_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSdPointAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSdPointAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSdPointAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSdPointAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSdPointAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSdPointAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSdPointAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSdPointAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSdPointAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSdPointAdminReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sd_point_admin_v1_sd_point_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sd_point_admin_v1_sd_point_admin_proto_goTypes,
		DependencyIndexes: file_api_sd_point_admin_v1_sd_point_admin_proto_depIdxs,
		MessageInfos:      file_api_sd_point_admin_v1_sd_point_admin_proto_msgTypes,
	}.Build()
	File_api_sd_point_admin_v1_sd_point_admin_proto = out.File
	file_api_sd_point_admin_v1_sd_point_admin_proto_rawDesc = nil
	file_api_sd_point_admin_v1_sd_point_admin_proto_goTypes = nil
	file_api_sd_point_admin_v1_sd_point_admin_proto_depIdxs = nil
}
